#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "framaforms"
name = "Yakforms"
description.en = "Create online webforms and surveys"
description.fr = "Créez des formulaires et questionnaires en ligne"

version = "1.1~ynh1"

maintainers = []

[upstream]
license = "GPL-2.0-only"
website = "https://yakforms.org"
code = "https://framagit.org/yakforms/yakforms"
fund = "https://soutenir.framasoft.org"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = true
sso = false
disk = "500M"
ram.build = "500M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    # Yakforms doesn't seem to be installable on a subdir, disabling it for now.
    # [install.path]
    # type = "path"
    # default = "/poll"

    [install.init_main_permission]
    help.en = "If no, only person with an account on your server will be able to create forms. In all cases, visitors will be able to reply to form."
    help.fr = "Si non, seule la personne disposant d'un compte sur votre serveur pourra créer des formulaires. Dans tous les cas, les visiteurs pourront répondre au formulaire."
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["de", "en", "es", "fr", "it", "pt"]
    default = "en"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

    [install.expiration]
    ask.en = "After how many weeks do the forms expire?"
    ask.fr = "Après combien de semaines les formulaires expirent-ils ?"
    help.en = "Set 0 to disable expiration"
    help.fr = "Mettre 0 pour désactiver l'expiration"
    type = "number"
    default = 0

    [install.deletion]
    ask.en = "After how many weeks is the forms deleted?"
    ask.fr = "Après combien de semaines les formulaires sont-ils supprimés ?"
    help.en = "Set 0 to disable deletion"
    help.fr = "Mettre 0 pour désactiver la suppression"
    type = "number"
    default = 0

[resources]
    [resources.sources.main]
    url = "https://framagit.org/yakforms/yakforms/-/archive/v1.1/yakforms-v1.1.tar.gz"
    sha256 = "da30fbd9821f84f21f06b7604232f0dc9b6b6a39738bb5326ee875f173300045"

    autoupdate.strategy = "latest_gitlab_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "postgresql",
        "curl",
        "libzip-dev",
        "php7.3-fpm",
        "php7.3-cli",
        "php7.3-gd",
        "php7.3-mysql",
        "php7.3-xml",
        "php7.3-ldap",
        "php7.3-mbstring",
        "php7.3-pgsql",
    ]

    [resources.database]
    type = "postgresql"
