#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    test_upgrade_from.79cdc1a139ff06805647cb56e5eab1d595ee0259.name = "1.0.3~ynh3"
