#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    test_upgrade_from.cb1ccdf04ff50b14826a96da2930570bd482f233.name = "1.0.3~ynh3"
    test_upgrade_from.cb1ccdf04ff50b14826a96da2930570bd482f233.args.path = "/"
